jingle:
  build: .
  links:
    - db
  command: test
  env_file:
    - env-example
  environment:
    VIRTUAL_HOST: jingle.prx.docker
    MIX_ENV: test
    LOCAL_ENV: 'true'
db:
  image: postgres
  env_file:
    - env-example
  ports:
    - "5432:5432"
