jingle:
  build: .
  volumes:
    - ./_build_docker_compose:/opt/app/_build
    - ./deps_docker_compose:/opt/app/deps
    - ./config:/opt/app/config
    - ./lib:/opt/app/lib
    - ./priv:/opt/app/priv
    - ./test:/opt/app/test
    - ./web:/opt/app/web
    - ./bin:/opt/app/bin
  env_file:
    - env-example
  links:
    - db
  ports:
    - "4000:4000"
  command: web
  environment:
    VIRTUAL_HOST: jingle.prx.docker
    MIX_ENV:
    LOCAL_ENV: 'true'
db:
  image: postgres
  env_file:
    - env-example
  ports:
    - "5432:5432"
