adze:
  build: .
  links:
    - db
  command: test
  env_file:
    - .env
  environment:
    VIRTUAL_HOST: adze.prx.docker
    MIX_ENV: test
    LOCAL_ENV: 'true'
db:
  image: postgres
  env_file:
    - .env
  ports:
    - "5432:5432"
